config/routes.rb
require 'sidekiq/web'
require 'sidekiq-cron'
Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
  [user, password] == ["api", "28ER67fi"]
end
Payments::Application.routes.draw do
  get 'notification/query'
  get 'notification/:notification/splashed' => 'notification#splashed', as: :splash_notification

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :banks
  get 'screenshot/show'

  get 'screenshots/:dir/:file', to: "screenshot#show",  :as => :screenshot, :defaults => {format: 'png'}

  get "home/index"
  get "api/queued_jobs"
  get "api/register_job"
  get "api/process_jobs"
  get "api/retry_jobs"
  get "api/clear-crons" => "api#clear_crons"
  post "api/register-job" => "api#register_job"
  post "api/remove-job" => "api#remove_job"
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'

end

app/models/bank.rb
class Bank < ActiveRecord::Base
  validates :account_id, presence: true
  validates :username, presence: true
  validates :name, presence: true
  validates :password, presence: true, on: :create
  validates :bank_type, presence: true
  validates :notation, presence: true
  validates :account_id, uniqueness: {scope: [:bank_type, :company_id], case_sensitive: false}, on: :create

  enum bank_types: {"Bank BCA"=>1, "Bank Mandiri"=>2, "Bank Mandiri Bisnis"=>3, "Bank BNI"=>4}
  enum bank_codes: {"bca"=>1, "mandiri"=>2, "mandiri_bisnis"=>3, "bni"=>4}
  enum statuses: [:inactive, :active]
  enum notations: {"Every 15 minutes" => "*/15 * * * *", "Every 30 minutes" => "0,30 * * * *", "Every hour"=>"0 */1 * * *","Every 2 Hour"=>"0 */2 * * *"}

  has_many :transactions
  has_many :duplicates, class_name: "DuplicateTransaction", foreign_key: "bank_id"
  has_many :balances, class_name: "Balance", foreign_key: "bank_id"
  belongs_to :user, class_name: "AdminUser", foreign_key: "user_id"
  scope :by_id, -> (id) {where("user_id = ?", id)}
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @banks = Bank.all
    respond_with(@banks)
  end

  def show
    respond_with(@bank)
  end

  def new
    @bank = Bank.new
    respond_with(@bank)
  end

  def edit
  end

  def create
    @bank = Bank.new(bank_params)
    @bank.save
    respond_with(@bank)
  end

  def update
    @bank.update(bank_params)
    respond_with(@bank)
  end

  def destroy
    @bank.destroy
    respond_with(@bank)
  end

  private
    def set_bank
      @bank = Bank.find(params[:id])
    end

    def bank_params
      params.require(:bank).permit(:name, :username, :password, :account_id, :company_id, :bank_type, :status)
    end
end

app/helpers/bank_helper.rb
require_relative 'logger_helper'
require_relative 'notification_helper'
require 'chronic'
# module Watir
#   class Hidden < Input
#     # Set the value of a hidden input field.
#     def set(value)
#       self.browser.execute_script('arguments[0].setAttribute("value", arguments[1]);', self, value)
#     end
#   end
# end
module BankHelper
  class Bank
    include LoggerHelper
    include NotificationHelper

    def initialize

    end
    def log (message, show_output=true, result='')
      @job_id.log_messages.create(message: message, name: @engine, result: (show_output && take_screenshot(message) || result),status:'')
      puts "[#{@engine}] #{message}" if show_output
    end
    def create_key (content)
      Digest::MD5.hexdigest(
        content
      ).to_s.scan(/.{4}/).join("-")
    end
    def prepare_browser(url, browser=:chrome)
      @current_browser = browser
      browser = Watir::Browser.start url, :phantomjs
      screen_width = browser.execute_script("return screen.width;")
      screen_height = browser.execute_script("return screen.height;")
      browser.driver.manage.window.resize_to(screen_width,screen_height)
      browser.driver.manage.window.move_to(0,0)
      browser
    end
    def take_screenshot (message)
      if @browser != nil
        file_name = create_key("#{message}-#{Time.now.to_s}")
        # file_name = "#{message.downcase.tr('^A-Za-z0-9 ','').gsub(' ', "-")}"
        if File.exists?(Rails.root.join("log/screenshots")) == false
          Dir.mkdir Rails.root.join("log/screenshots")
        end
        if File.exists?(Rails.root.join("log/screenshots/#{@job_id.job_id}")) == false
          Dir.mkdir Rails.root.join("log/screenshots/#{@job_id.job_id}")
        end
        if @browser.exists?
          @browser.screenshot.save(Rails.root.join("log/screenshots/#{@job_id.job_id}/#{file_name}.png"))
          ["http://crawlers.terapkan.com",
            Rails.application.routes.url_helpers.screenshot_path(format: :png, file: file_name, dir: @job_id.job_id)
          ].join('')
        else
          ''
        end
      else
        ''
      end
    end
    def caught_signal (bank)
      bank.status == 'inactive'
    end
    def process_data (mutations, bank, start_date)

      # ActiveRecord::Base.connection.execute("ALTER TABLE `transactions` auto_increment = #{Transaction.count+1}; ");
      log "Inserting data"
      mutation_logs = {
        :new => 0,
        :update => 0,
        :duplicates => 0,
        :old => 0
      }
      mutations.uniq.each do |results|
        if results.include?('old_key') and Transaction.where("`serial_key` = ?", results["old_key"]).count == 1
          mutation_logs[:old]+=1
          trans = Transaction.find_by(serial_key: results["old_key"])
          trans.serial_key = results["serial_key"]
          trans.date = results["date"]
          trans.save
        elsif Transaction.where("`serial_key` = ?", results["serial_key"]).count > 0
          mutation_logs[:update]+=1
          trans = Transaction.find_by(serial_key: results["serial_key"])
          trans.date = results["date"]
          trans.notes = results["notes"]
          trans.save
        elsif Transaction.where("`serial_key` = ?", results["serial_key"]).count == 0
          if @bank.transactions.where("date between ? and ? and amount = ?", Chronic.parse("7 days ago", :now => Chronic.parse(results["date"])).strftime('%Y-%m-%d'), results["date"], results["amount"]).count == 1 and ['mandiri', 'mandiri-bisnis', 'mandiri_bisnis'].include?(@bank.bank_type)
            @bank.duplicates.find_or_create_by(serial_key: results["serial_key"]){|trans|
              trans.date = results["date"]
              trans.amount = results["amount"]
              trans.notes = results["notes"]
              trans.content = @bank.transactions.where("date between ? and ? and amount = ?", Chronic.parse("7 days ago", :now => Chronic.parse(results["date"])).strftime('%Y-%m-%d'), results["date"], results["amount"]).first.id
              mutation_logs[:duplicates]+=1
            }

          else
            mutation_logs[:new]+=1
            new_mutation = @bank.transactions.create(notes: results["notes"], date: results["date"], amount: results["amount"], serial_key: results["serial_key"])
            results["id"] = new_mutation.id
          end
        end
      end
      if mutation_logs[:new] >= 0
        notify "New transactions in #{@bank.name}", "Total #{mutation_logs[:new]} new transactions found in #{@bank.name}. Please take a look at it", @bank.user_id
      end
      log "Summary of mutations : #{mutation_logs}"
      log "check for duplicate records"

      mutations.group_by {|e| e}.each do |value|
        results = value[0]
        if value[1].count > 1 and DuplicateTransaction.where("`serial_key` = ?", results["serial_key"]).count == 0
          DuplicateTransaction.create(notes: results["notes"], date: results["date"], amount: results["amount"], bank_id: bank.id, content: value[1].to_json, serial_key: results["serial_key"])
          log "Making note for duplicate records. Serial Key : #{results["serial_key"]}"
        end
      end
      log("saving raw results", false, mutations.to_json)
      kill_hanging_process
      log "done"
      trigger_callback(@bank.name, "Bank Crawler completed", "success")
    end
    def kill_hanging_process
      current_browser = "chrome" if @current_browser == :chrome
      current_browser = "firefox" unless @current_browser == :chrome
      output = `ps -ef | grep #{current_browser}`.split("\n")
      pids = []
      output.each do |line|
        data = line.split(" ")
        date = Chronic.parse("today #{data[4]}")
        # puts Time.now - date
        `kill -9 #{data[1]}` if Time.now - date > 10*60 # kill all firefox process more than 10 minutes range. since it's useless
      end
      `rm core.*`
      log "clean up some unnecessary files"
    end
    def catch_error(e, type)
      if @browser != nil
        message = @browser.alert.text if @browser.alert.exists? and type == 'alert'
        message = e.message unless @browser.alert.exists? and type == 'alert'
      else
        message = e.message
      end
      message = "Error Occured (#{message})"
      log message
      close_browser
      backtrace_string = ["Trace : "]
      e.backtrace.each {|line| backtrace_string << line}
      @job_id.update(status: 'error')
      log(backtrace_string.join("\n"), false)
      trigger_callback(@bank.name, message, "error")
      raise e.message
    end
    def trigger_callback(bank_name, message, status)
      return if File.exists?("#{Rails.root.join("tmp")}/callbacks.json") == false
      callbacks = JSON.parse(File.read("#{Rails.root.join("tmp")}/callbacks.json"))
      if callbacks.include?("bank-#{bank_name.gsub(' ', '-').downcase}") and callbacks["bank-#{bank_name.gsub(' ', '-').downcase}"].size > 0
        log "Triggering registered callbacks"
        callbacks["bank-#{bank_name.gsub(' ', '-').downcase}"].each do |callback|
          callback["arguments"][0]["data"]["result"] = {
            "status"=>status,
            "message"=>message,
          }
          Kernel.const_get(callback["worker"]).perform_async(callback["arguments"][0])
        end
        callbacks["bank-#{bank_name.gsub(' ', '-').downcase}"] = []
        File.open("#{Rails.root.join("tmp")}/callbacks.json", "w"){|file| file.write(callbacks.to_json)}
        log "Cleanup callbacks"
      end
    end
    def close_browser
      @browser.close if @browser != nil and @browser.exists?
    end
  end
end

app/views/banks/_form.html.erb
<%= form_for(@bank) do |f| %>
  <% if @bank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank.errors.count, "error") %> prohibited this bank from being saved:</h2>

      <ul>
      <% @bank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.text_field :account_id %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.text_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :bank_type %><br>
    <%= select_tag(:bank_type, options_for_select(Bank.bank_types)) %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= select_tag(:status, options_for_select(Bank.statuses)) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banks/edit.html.erb
<h1>Editing bank</h1>

<%= render 'form' %>

<%= link_to 'Show', @bank %> |
<%= link_to 'Back', banks_path %>

app/views/banks/index.html.erb
<h1>Listing banks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Password</th>
      <th>Account</th>
      <th>Company</th>
      <th>Bank type</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banks.each do |bank| %>
      <tr>
        <td><%= bank.name %></td>
        <td><%= bank.username %></td>
        <td><%= bank.password %></td>
        <td><%= bank.account_id %></td>
        <td><%= bank.company_id %></td>
        <td><%= bank.bank_type %></td>
        <td><%= bank.status %></td>
        <td><%= link_to 'Show', bank %></td>
        <td><%= link_to 'Edit', edit_bank_path(bank) %></td>
        <td><%= link_to 'Destroy', bank, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bank', new_bank_path %>

app/views/banks/new.html.erb
<h1>New bank</h1>

<%= render 'form' %>

<%= link_to 'Back', banks_path %>

app/views/banks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bank.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @bank.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @bank.password %>
</p>

<p>
  <strong>Account:</strong>
  <%= @bank.account_id %>
</p>

<p>
  <strong>Company:</strong>
  <%= @bank.company_id %>
</p>

<p>
  <strong>Bank type:</strong>
  <%= @bank.bank_type %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bank.status %>
</p>

<%= link_to 'Edit', edit_bank_path(@bank) %> |
<%= link_to 'Back', banks_path %>